### ISSUE TITLE
Video Object Detection

### ISSUE THREAD

**Issue by rodrigo-reboucas** [vbalnt/bold#2]
It is possible to use BOLD as TFeat, input: object image and video; Output: object detection in video?

I would like to use the code in OpenCV to generate this result: http://docs.opencv.org/3.2.0/dc/d16/tutorial_akaze_tracking.html

**Comment by vbalnt** [comment]
Hi, it is possible yes, although it needs some work on interfacing with the standard openCV things like `cv::Keypoint` etc. 

I would suggest to take a look on Steffen's @urbste [BOLD implementation](https://github.com/urbste/mdBRIEF), which is much better, cleaner and interfaces directly with openCV. 

You should be able to use his code in the way you want.

**Comment by rodrigo-reboucas** [comment]
Thank you, excellent article.
